/** IPC 通道名（主进程与 preload 约定） */
export const IPC = {
  configGet: 'config:get',
  configSet: 'config:set',
  configPreview: 'config:preview-appearance',
  configStorageGet: 'config:storage',
  configOpenDirectory: 'config:open-directory',
  cacheInventory: 'cache:inventory',
  cacheClear: 'cache:clear',
  cacheLocation: 'cache:location',
  cacheChooseDirectory: 'cache:choose-directory',
  cacheResetDirectory: 'cache:reset-directory',
  cacheOpenDirectory: 'cache:open-directory',
  appRestart: 'app:restart',
  emoticonCatalogGet: 'emoticons:get',
  emoticonCatalogPush: 'emoticons:push',
  overlayPushDanmaku: 'danmaku:push',
  overlayClearDanmaku: 'danmaku:clear',
  overlayPushConfig: 'config:push',
  overlayPushStats: 'overlay:stats',
  overlayGiftCatalog: 'overlay:gift-catalog',
  overlayRendered: 'overlay:rendered',
  giftCatalogStatus: 'gifts:status',
  giftCatalogGet: 'gifts:get-status',
  giftCatalogRefresh: 'gifts:refresh',
  giftPriceSet: 'gifts:set-price',
  statisticsQuery: 'statistics:query',
  statisticsExport: 'statistics:export',
  statisticsChats: 'statistics:chats',
  settingsSection: 'settings:section',
  douyuStatus: 'douyu:status',
  douyuReconnect: 'douyu:reconnect',
  windowOpenSettings: 'window:open-settings',
  windowOpenHome: 'window:open-home',
  windowClose: 'window:close',
  windowMinimize: 'window:minimize',
  windowToggleMaximize: 'window:toggle-maximize',
  windowStateGet: 'window:get-state',
  windowStatePush: 'window:state',
  windowDragStart: 'window:drag-start',
  windowDragMove: 'window:drag-move',
  windowDragEnd: 'window:drag-end',
  homePushLogo: 'home:push-logo',
  appGetVersion: 'app:get-version',
  /** 检测 GitHub Release 是否有新版本（主进程缓存 + 限频） */
  appCheckUpdate: 'app:check-update',
  /** 主进程校验后打开外链（更新下载等） */
  appOpenExternal: 'app:open-external',
  /** 后台检测完成后推送给主界面 */
  appUpdatePush: 'app:update-push',
  /** 枚举显示器（飘屏设置） */
  displayList: 'display:list'
} as const
