const { build, Platform, Arch } = require('electron-builder')
const { copyFileSync, mkdirSync, readFileSync, writeFileSync } = require('node:fs')
const { createHash } = require('node:crypto')
const { basename, join, resolve } = require('node:path')
const { cleanGeneratedDirectory } = require('./clean-dist.cjs')

if (process.platform !== 'win32') throw new Error('Starveil 只构建 Windows 版本。')
const root = resolve(__dirname, '..')
;(async () => {
  cleanGeneratedDirectory(root, join('release', '.build'))
  const artifacts = await build({ targets: Platform.WINDOWS.createTarget('portable', Arch.x64),
    publish: 'never', config: { directories: { output: 'release/.build' } } })
  const executables = artifacts.filter(file => file.toLowerCase().endsWith('.exe'))
  if (executables.length !== 1) throw new Error('没有生成唯一的 Windows 便携程序。')
  mkdirSync(join(root, 'release'), { recursive: true })
  const output = join(root, 'release', basename(executables[0]))
  copyFileSync(executables[0], output)
  const checksum = createHash('sha256').update(readFileSync(output)).digest('hex')
  writeFileSync(output + '.sha256', `${checksum}  ${basename(output)}\n`, 'utf8')
  const manifest = require('../package.json')
  const notices = join(root, 'release', `${manifest.build.productName}-${manifest.version}-NOTICES.txt`)
  copyFileSync(join(root, 'THIRD_PARTY_NOTICES.md'), notices)
  cleanGeneratedDirectory(root, join('release', '.build'))
  console.log('Windows 程序：' + output)
  console.log('SHA-256 校验：' + output + '.sha256')
  console.log('开源许可声明：' + notices)
})().catch(error => { console.error(error); process.exitCode = 1 })
